octave.password.change.password:
    path: '%octave.password.change.password.path%'
    defaults:
       _controller: Octave\PasswordBundle\Controller\PasswordChangeController:changePassword

octave.password.renew.password:
    path: '%octave.password.renew.password.path%'
    defaults:
       _controller: Octave\PasswordBundle\Controller\PasswordChangeController:renewPassword

octave.password.renew.password.request:
  path: '%octave.password.renew.password.request.path%'
  defaults:
    _controller: Octave\PasswordBundle\Controller\PasswordChangeController:request

octave.password.auth.confirmation:
  path: '%octave.password.auth.confirmation.path%'
  defaults:
    _controller: Octave\PasswordBundle\Controller\AdminAuthController::confirmation

octave.password.auth.resend:
  path: '%octave.password.auth.resend.path%'
  defaults:
    _controller: Octave\PasswordBundle\Controller\AdminAuthController::resendCode

octave.password.invite:
  path: '%octave.password.invite.path%'
  defaults:
    _controller: Octave\PasswordBundle\Controller\AdminAuthController::invite