octave.password.change.password:
    path: '%octave.password.change.password.path%'
    defaults:
       _controller: Octave\PasswordBundle\Controller\PasswordChangeController:changePassword

octave.password.renew.password:
    path: '%octave.password.renew.password.path%'
    defaults:
       _controller: Octave\PasswordBundle\Controller\PasswordChangeController:renewPassword

octave.password.renew.password.request:
  path: '%octave.password.renew.password.request.path%'
  defaults:
    _controller: Octave\PasswordBundle\Controller\PasswordChangeController:request