parameters:
    octave.password.change.password.path: 'password/change'
    octave.password.renew.password.path: 'password/renew/{token}'
    octave.password.renew.password.request.path: 'password/renew-request'

services:

    _defaults:
        public: true
        autowire: true

    Octave\PasswordBundle\Controller\PasswordChangeController:
        public: true
        autowire: true
        tags:
            - { name: 'container.service_subscriber' }
            - { name: 'controller.service_arguments' }

    Octave\PasswordBundle\EventListener\PasswordChangeSubscriber:
        arguments:
            - '@router'
            - '@security.token_storage'
            - '%octave.password.expiration.days%'
            - '%octave.password.redirect.route%'
            - '%octave.password.send.email%'
            - '%octave.password.mailer.class%'
        tags:
            - { name: kernel.event_subscriber }

    Octave\PasswordBundle\Form\ChangePasswordType:
        arguments:
                $translator: '@translator'
                $passwordHasher: '@security.user_password_hasher'
                $passwordHistoryRepository: '@Octave\PasswordBundle\Repository\PasswordHistoryRepository'
                $entityManager: '@doctrine.orm.entity_manager'
                $askCurrentPassword: '%octave.password.ask.current.password%'
                $userClass: '%octave.password.user.class%'
                $minLength: '%octave.password.min.length%'
                $maxLength: '%octave.password.max.length%'
                $complexityLevel: '%octave.password.complexity.level%'
                $keepHistory: '%octave.password.keep.history%'
                $historyCount: '%octave.password.history.count%'
        tags:
            - { name: form.type }

    Octave\PasswordBundle\Repository\PasswordHistoryRepository:
        arguments:
            $registry: '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }